#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=10
ENV_FILE=.env.local
SITE=help.sebastianbrookes.com

cd "$(dirname "$0")/.."

banner "Help assistant: go live at $SITE"

stage "GitHub: push main"
say "Vercel builds from GitHub, so it needs your latest commits, including vercel.json."
note "vercel.json makes each Vercel build deploy the Convex functions too, so they stay in step."
if ! git ls-files --error-unmatch vercel.json >/dev/null 2>&1; then
  warn "vercel.json isn't committed yet."
  if confirm "Commit vercel.json now?"; then
    git add vercel.json
    git commit -m "Deploy Convex functions from the Vercel build"
  fi
fi
git status -sb | head -1
if confirm "Run git push origin main now?"; then
  git push origin main
else
  SKIPPED+=("push main to GitHub (run: git push origin main)")
fi
pause

stage "Convex: create the production deployment"
say "This pushes the Convex functions and schema to the project's production deployment."
say "The production deployment is created the first time you deploy."
step "When it asks whether to push to prod, answer yes."
if confirm "Run pnpm exec convex deploy now?"; then
  pnpm exec convex deploy
else
  SKIPPED+=("Convex production deployment (run: pnpm exec convex deploy)")
fi
pause

stage "OpenRouter: check the credit"
say "The \$5 credit you bought during dev setup is the demo's whole budget."
open_url "https://openrouter.ai/settings/credits"
step "Check the balance shows about \$5. If it doesn't, buy enough to bring it to \$5."
step "Check that auto top-up is off. With it off, spending can't go past the credit."
pause "Press Enter once the credit is there and auto top-up is off"

stage "OpenRouter: demo key"
say "The live demo gets its own key. Build and test scripts keep using the build/test key."
open_url "https://openrouter.ai/settings/keys"
step "Create a key named help-assistant-demo."
step "Set its credit limit to \$10 and make it reset monthly."
note "If the form has no reset option, set a \$10 limit anyway and tell the agent."
step "Copy the key now. OpenRouter shows it only once."
ask_secret OPENROUTER_API_KEY "Paste the key (starts sk-or-):"
note "The key goes only into Convex production, never into .env.local or the browser."
if printf '%s' "$OPENROUTER_API_KEY" | pnpm exec convex env set --prod OPENROUTER_API_KEY; then
  printf '  %s✓ set%s OPENROUTER_API_KEY on the Convex production deployment\n' "$GREEN" "$RESET"
else
  SKIPPED+=("OPENROUTER_API_KEY on Convex prod (run: pnpm exec convex env set --prod OPENROUTER_API_KEY)")
fi
pause

stage "Convex: load the starting data"
say "This loads the committed Help articles, IT team notes, 8 weeks of history,"
say "starting Gap groups, and Suggested questions. It makes no AI calls."
note "The history ends on the day you load it, so loading it near launch keeps it fresh."
if confirm "Run pnpm exec convex run --prod seed:load now?"; then
  pnpm exec convex run --prod seed:load
else
  SKIPPED+=("starting data on prod (run: pnpm exec convex run --prod seed:load)")
fi
pause

stage "Smoke test: one real question on prod"
say "This asks one question through the real model using the demo key."
note "It costs a fraction of a cent and uses one of the day's 250 AI calls."
if pnpm exec convex run --prod questions:ask '{"visitorId":"wizard-smoke-test","text":"How do I order lab supplies from Fisher?"}' \
  && pnpm exec convex run --prod questions:list '{"visitorId":"wizard-smoke-test"}'; then
  printf '  %s✓ the assistant answered on prod%s\n' "$GREEN" "$RESET"
else
  warn "the question failed; check the error above and the logs with: pnpm exec convex logs --prod"
  SKIPPED+=("a working smoke-test question on prod")
fi
pause

stage "Convex: production deploy key"
say "Vercel needs this key so each build can deploy the Convex functions to production."
note "Opening the Convex dashboard on the production deployment."
pnpm exec convex dashboard --prod >/dev/null 2>&1 || open_url "https://dashboard.convex.dev"
step "Check the deployment switcher at the top says Production."
step "Open Settings and find the deploy key section."
step "Click Generate Production Deploy Key and copy it."
note "Keep it on your clipboard for the next stage. The wizard doesn't store it."
pause "Press Enter once the key is copied"

stage "Vercel: import the repo"
open_url "https://vercel.com/new"
step "Use the same Vercel account that has sebastianbrookes.com."
step "Import sebastianbrookes/gapfinder."
step "Leave Framework Preset as Vite. vercel.json supplies the build command."
step "Under Environment Variables, add CONVEX_DEPLOY_KEY with the key you copied."
step "Click Deploy and wait for the build to finish."
say ""
say "Then limit the key to production builds:"
step "Project → Settings → Environment Variables → CONVEX_DEPLOY_KEY → Edit."
step "Leave only Production ticked, then save."
note "Otherwise a preview build of another branch would deploy its functions to prod."
pause "Press Enter once the first deploy has succeeded"

stage "Vercel: add $SITE"
say "Your domain already uses Vercel's nameservers, so no DNS records should be needed."
step "In the new project: Settings → Domains → Add Domain."
step "Enter $SITE and connect it to Production."
step "Wait until it shows Valid Configuration."
note "If Vercel asks for a DNS record instead, the project is in a different account or team."
pause "Press Enter once the domain shows as valid"
until code=$(curl -s -o /dev/null -w '%{http_code}' "https://$SITE") && [[ "$code" == 200 ]]; do
  warn "https://$SITE returned ${code:-no response}. The HTTPS certificate can take a minute."
  confirm "Check again?" || { SKIPPED+=("https://$SITE serving the site"); break; }
done
[[ "${code:-}" == 200 ]] && printf '  %s✓ https://%s is live%s\n' "$GREEN" "$SITE" "$RESET"
pause

stage "Check the full flow on a phone and a desktop"
open_url "https://$SITE"
say "Do this once on your phone and once on a desktop:"
step "Click a Suggested question and get an answer."
step "Type a question the Help articles cover and get an answer."
step "Type a question they don't cover and see it logged as a Gap."
step "In the IT team panel (its own tab on a phone), find that Gap's group and click Draft article."
step "Click Approve and check the new Help article answers the question."
pause "Press Enter once both devices work end to end"

finish
say "Next: tell the agent the results so it can tick off ticket 10."
